import { buildPaperMap } from '../lib/core/tree';
import type { Paper, PaperMap } from '../lib/core/types';

const papers: Paper[] = [
  { id: 'root', title: 'Product Design', description: 'The top-level vision for the product.', content: 'Product design aligns user needs, technical constraints, and business goals into one coherent system. This root paper frames the major decision areas and acts as the entry point for the whole canvas.', parentId: null, childIds: ['ux', 'tech', 'biz'] },
  { id: 'ux', title: 'UX Design', description: 'User experience and interaction design principles.', content: 'UX design shapes the structure and feel of the product. It covers navigation, flows, testing, and the quality of each interaction from first use to long-term retention.', parentId: 'root', childIds: ['ia', 'visual', 'proto', 'research', 'copy', 'motion', 'access', 'test', 'iterate'] },
  { id: 'tech', title: 'Technology', description: 'Technical architecture and implementation.', content: 'The technology branch turns product intent into durable systems. It covers frontend architecture, backend contracts, and the operational surface needed to ship and maintain the product.', parentId: 'root', childIds: ['frontend', 'backend', 'infra'] },
  { id: 'biz', title: 'Business', description: 'Business strategy and metrics.', content: 'Business design defines how the product grows and sustains itself. It includes acquisition, monetization, and the metrics that tell whether the product is creating lasting value.', parentId: 'root', childIds: ['growth', 'monetize'] },
  { id: 'ia', title: 'Information Architecture', description: 'Structure and organization of content.', content: 'Information architecture decides how content and functionality are grouped so people can predict where things live and how to move through the system.', parentId: 'ux', childIds: ['sitemap', 'taxonomy'] },
  { id: 'visual', title: 'Visual Design', description: 'Color, typography, and layout systems.', content: 'Visual design gives the product a consistent language through type, rhythm, spacing, and color. It turns structure into an interface that feels legible and intentional.', parentId: 'ux', childIds: ['color', 'type'] },
  { id: 'proto', title: 'Prototyping', description: 'Low and high fidelity prototypes.', content: 'Prototyping makes ideas tangible early. It helps validate flows, transitions, and interactions before the full implementation cost is paid.', parentId: 'ux', childIds: [] },
  { id: 'research', title: 'User Research', description: 'Interviews, surveys, and usability tests.', content: 'Research grounds product decisions in evidence. It connects design direction to observed behavior, unmet needs, and real-world constraints.', parentId: 'ux', childIds: [] },
  { id: 'copy', title: 'Copywriting', description: 'Voice, tone, and microcopy.', content: 'Copywriting shapes how the interface communicates intent. Clear labels, guidance, and feedback text reduce friction and increase confidence.', parentId: 'ux', childIds: [] },
  { id: 'motion', title: 'Motion Design', description: 'Transitions and micro-interactions.', content: 'Motion design makes change visible. It can clarify hierarchy, continuity, and causality when screens, states, and layers shift.', parentId: 'ux', childIds: [] },
  { id: 'access', title: 'Accessibility', description: 'WCAG compliance and inclusive design.', content: 'Accessibility ensures the interface remains perceivable and operable for a wide range of users and assistive technologies.', parentId: 'ux', childIds: [] },
  { id: 'test', title: 'Usability Testing', description: 'Testing with real users.', content: 'Usability testing surfaces practical friction in tasks, labels, expectations, and pacing before those issues scale into the shipped product.', parentId: 'ux', childIds: [] },
  { id: 'iterate', title: 'Iteration', description: 'Continuous improvement cycles.', content: 'Iteration turns each release into feedback for the next one. Teams learn, adjust, and improve the product in smaller, compounding steps.', parentId: 'ux', childIds: [] },
  { id: 'frontend', title: 'Frontend', description: 'React, TypeScript, CSS.', content: 'Frontend engineering delivers the product surface people use directly. It coordinates rendering, state, interaction, and visual polish in the browser.', parentId: 'tech', childIds: ['components', 'state', 'routing'] },
  { id: 'backend', title: 'Backend', description: 'API design and data modeling.', content: 'Backend systems define how data is stored, validated, and exchanged. They provide the contract that keeps product behavior reliable across clients and services.', parentId: 'tech', childIds: [] },
  { id: 'infra', title: 'Infrastructure', description: 'Cloud, CI/CD, monitoring.', content: 'Infrastructure supports deployment, reliability, and observability. It determines how safely and repeatedly a team can ship changes.', parentId: 'tech', childIds: [] },
  { id: 'components', title: 'Component Library', description: 'Reusable UI components.', content: 'A component library creates a shared interface vocabulary so screens can move faster without losing consistency.', parentId: 'frontend', childIds: [] },
  { id: 'state', title: 'State Management', description: 'Global and local state patterns.', content: 'State management decides how UI data flows through the system and how views remain predictable as they react to user input and async events.', parentId: 'frontend', childIds: [] },
  { id: 'routing', title: 'Routing', description: 'Client-side navigation.', content: 'Routing maps interface state to navigable URLs and transitions, giving users stable entry points and recoverable navigation paths.', parentId: 'frontend', childIds: [] },
  { id: 'sitemap', title: 'Sitemap', description: 'Page hierarchy and navigation.', content: 'A sitemap captures the top-level shape of the product and helps teams reason about how major areas connect.', parentId: 'ia', childIds: [] },
  { id: 'taxonomy', title: 'Taxonomy', description: 'Content classification system.', content: 'Taxonomy provides naming and grouping rules that keep content discoverable and scalable as the product grows.', parentId: 'ia', childIds: [] },
  { id: 'color', title: 'Color System', description: 'Palette and semantic tokens.', content: 'A color system defines semantic roles for hue, tone, and contrast so screens can be expressive without becoming inconsistent.', parentId: 'visual', childIds: [] },
  { id: 'type', title: 'Typography', description: 'Font scale and text styles.', content: 'Typography sets the reading rhythm of the interface. It creates hierarchy, improves legibility, and stabilizes the overall visual voice.', parentId: 'visual', childIds: [] },
  { id: 'growth', title: 'Growth', description: 'Acquisition and retention strategies.', content: 'Growth connects product quality to reach and retention. It focuses on how people discover the product, activate, and keep coming back.', parentId: 'biz', childIds: [] },
  { id: 'monetize', title: 'Monetization', description: 'Revenue models and pricing.', content: 'Monetization defines how value is exchanged. It balances pricing, packaging, and incentives with user trust and business health.', parentId: 'biz', childIds: [] },
];

export function buildDemoPaperMap(): PaperMap {
  return buildPaperMap(papers);
}
